---
version: "3"
services:
  freeradius:
    image: goofball222/freeradius
    container_name: freeradius
    user: "1000:1000"
    environment:
      - PUID=999
      - PGID=999
      - TZ=Etc/UTC
#      - RADIUSD_OPTS=-xx # Enable this for FreeRadius extra log verbosity/degub
#      - RADIUSD_OPTS=-X
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/:/etc/raddb
      - ./logs:/var/log/radius
    ports:
      - 10.0.18.12:1812:1812/udp
      - 10.0.18.12:1813:1813/udp
    restart: unless-stopped

